apiVersion: v1
kind: Pod
metadata:
  name: pod_
spec:
  containers:
    - name: container_name
      image: DOCKER_USER/PRIVATE_REPO_NAME:latest
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
  imagePullSecrets:
    - name: myregistrykey
